/**
 * ONE MORE RUSH — Unified SEO Content & Route Registry (Single Source of Truth)
 * Shared between build-time static HTML prerendering and client-side runtime SEO services.
 */

export const DEFAULT_SITE_URL = 'https://onemorerush.com';

export const ALL_GAMES = [
  { id: 'aim', name: 'AIM', icon: '🎯', tagline: 'Test your reaction speed & target precision.' },
  { id: 'dodge', name: 'DODGE', icon: '🛡️', tagline: 'Survive hazard waves, collect gems & risk everything.' },
  { id: 'stack', name: 'STACK', icon: '🧱', tagline: 'Build the tallest tower with precision timing & rhythm.' },
  { id: 'number-rush', name: 'NUMBER RUSH', icon: '🔢', tagline: 'Fast-paced mental math under intense pressure.' },
  { id: 'memory', name: 'MEMORY', icon: '🧠', tagline: 'Expand pattern recall & visual sequence retention.' },
  { id: 'color-maze', name: 'COLOR MAZE', icon: '🎨', tagline: 'Paint every labyrinth corridor & slide to the finish.' },
];

export const ROUTE_SEO_DATA = {
  '/': {
    path: '/',
    title: 'ONE MORE RUSH — Free Online Arcade Games',
    description: 'Play free online arcade games on One More Rush. Test your aim, reflexes, memory, timing, speed and precision across six fast-paced browser games.',
    h1: 'ONE MORE RUSH — Free Online Arcade Games',
    type: 'website',
    overview: 'One More Rush is an instant-play browser arcade featuring six responsive, skill-based games designed for high-score chasing, daily challenges, and personal bests. No installations, pay-to-win mechanics, or friction.',
    features: [
      'Six original arcade games testing aim, reflexes, timing, math, memory, and pathfinding.',
      'Daily rotating challenges with Quick Win and Extreme Rush difficulty tiers.',
      'Rush Points (RP) economy for unlocking cosmetic avatar frames, titles, and victory effects.',
      'Instant browser-local progress saving and seamless optional cloud account upgrades.',
    ],
  },
  '/games/aim': {
    path: '/games/aim',
    gameId: 'aim',
    gameName: 'AIM',
    genre: 'Precision Target Arcade',
    title: 'AIM — Free Online Aim & Target Precision Game | One More Rush',
    description: 'Test your reaction speed, mouse accuracy, and target precision in AIM, a fast-paced browser arcade skill game on One More Rush.',
    h1: '🎯 AIM — Target Precision & Reflex Game',
    subtitle: 'How fast can you react?',
    type: 'game',
    overview: 'AIM is a high-speed target acquisition arcade game designed to measure and sharpen your clicking speed, reaction time, and cursor accuracy under time pressure.',
    objective: 'Click or tap spawned target circles as rapidly and accurately as possible before the round countdown expires.',
    howToPlay: [
      'Click each spawned circular target as soon as it appears on screen.',
      'Targets become smaller and move faster as your run progresses.',
      'Chain consecutive successful hits without misclicking to build your combo multiplier.',
      'Keep pace with the countdown clock to maximize total score before time expires.',
      'Aim for a high score above 20,000 to unlock the Sharpshooter achievement.',
    ],
    controls: 'Desktop: Left Click / Mouse Pointer. Mobile / Tablet: Direct Screen Tap on targets.',
    skillsTested: 'Reaction Speed, Hand-Eye Coordination, Target Tracking, Click Accuracy.',
    proTip: 'Never rush a wild click. Maintaining your consecutive hit combo provides more points than frantic misclicking.',
    flowSteps: ['TARGET SPAWNS', 'CLICK IT', 'BUILD COMBO', 'BEAT YOUR BEST'],
  },
  '/games/dodge': {
    path: '/games/dodge',
    gameId: 'dodge',
    gameName: 'DODGE',
    genre: 'Survival Reflex Arcade',
    title: 'DODGE — Free Reflex & Survival Arcade Game | One More Rush',
    description: 'Survive relentless hazard waves, dodge danger zones, and collect score multipliers in DODGE, a free survival arcade game on One More Rush.',
    h1: '🛡️ DODGE — Reflex Survival & Hazard Game',
    subtitle: 'Survive. Collect. Risk everything.',
    type: 'game',
    overview: 'DODGE is an intense survival arcade game where you pilot your energy core through bullet-hell hazard waves, collect glowing multipliers, and weave through danger.',
    objective: 'Survive dynamic obstacle patterns, graze hazard borders for bonus proximity score, and collect score gems without taking a fatal hit.',
    howToPlay: [
      'Steer your player core away from lethal red hazard shapes and incoming laser beams.',
      'Collect yellow gems to charge your score multiplier up to 5x.',
      'Graze close to dangerous hazard edges for high-risk proximity score bonuses.',
      'Survive special event waves including Laser Grid, Meteor Shower, and Bullet Hell.',
      'Survive beyond 20,000 points to unlock the prestigious Survivor badge.',
    ],
    controls: 'Desktop: WASD or Arrow Keys. Mobile / Tablet: Floating Virtual Touch Joystick / Swipe.',
    skillsTested: 'Reflexes, Spatial Awareness, Micro-Movement, Risk-Reward Evaluation.',
    proTip: 'Stay near the center of the arena during calm moments, then pull towards outer boundaries only when navigating dense waves.',
    flowSteps: ['HAZARDS SPAWN', 'DODGE ATTACKS', 'COLLECT GEMS', 'SURVIVE'],
  },
  '/games/stack': {
    path: '/games/stack',
    gameId: 'stack',
    gameName: 'STACK',
    genre: 'Timing & Balance Arcade',
    title: 'STACK — Free Block Stacking & Timing Game | One More Rush',
    description: 'Build the tallest isometric tower in STACK. Master precision timing, balance moving blocks, and trigger perfect combo chains on One More Rush.',
    h1: '🧱 STACK — Isometric Tower & Timing Game',
    subtitle: 'How high can you build?',
    type: 'game',
    overview: 'STACK is a rhythmic precision timing game where oscillating 3D blocks must be placed with pinpoint accuracy on top of a growing tower without losing surface area.',
    objective: 'Drop each oscillating block directly aligned with the block beneath it to construct the highest skyscraper possible.',
    howToPlay: [
      'Time your tap or spacebar press to drop the moving block onto the base.',
      'Any overhanging portion is sliced off, reducing the width of subsequent blocks.',
      'Land exact alignments within the perfect threshold to hear harmonic musical notes.',
      'Chain 3 or more consecutive perfect placements to trigger expanding block combos.',
      'Reach tower height 25+ to unlock the Builder achievement badge.',
    ],
    controls: 'Desktop: Spacebar or Mouse Click. Mobile / Tablet: Screen Tap to drop/place block.',
    skillsTested: 'Timing Precision, Rhythm, Depth Perception, Visual Alignment.',
    proTip: 'Watch the leading edge of the moving block rather than the center for accurate release timing.',
    flowSteps: ['BLOCK MOVES', 'TIME DROP', 'PERFECT ALIGN', 'STACK HIGHER'],
  },
  '/games/number-rush': {
    path: '/games/number-rush',
    gameId: 'number-rush',
    gameName: 'NUMBER RUSH',
    genre: 'Speed Mental Math Arcade',
    title: 'NUMBER RUSH — Free Fast Math & Number Game | One More Rush',
    description: 'Solve rapid arithmetic challenges and test your quick mental math calculations under pressure in NUMBER RUSH on One More Rush.',
    h1: '🔢 NUMBER RUSH — Mental Arithmetic Speed Game',
    subtitle: "Think fast. Numbers don't wait.",
    type: 'game',
    overview: 'NUMBER RUSH is a rapid-fire arithmetic calculation game that challenges your mental math processing, decision speed, and numerical reflexes against a ticking timer.',
    objective: 'Solve arithmetic equations in fractions of a second and select the matching answer tile before time runs out.',
    howToPlay: [
      'Analyze the displayed math problem (addition, subtraction, multiplication, division).',
      'Select the correct answer from the four available answer options.',
      'Correct answers award points and add crucial bonus seconds to your timer.',
      'Consecutive correct streaks trigger high-scoring Rush Mode multipliers.',
      'Score 15,000+ points to claim the Calculator badge in your Rush Locker.',
    ],
    controls: 'Desktop: Number Keys (1-4) or Click. Mobile / Tablet: Tap directly on answer tile.',
    skillsTested: 'Mental Arithmetic, Rapid Information Processing, Working Memory.',
    proTip: 'Use parity (odd/even) and last-digit estimation to eliminate impossible answers instantly.',
    flowSteps: ['EQUATION APPEARS', 'CALCULATE FAST', 'PICK ANSWER', 'EXTEND TIME'],
  },
  '/games/memory': {
    path: '/games/memory',
    gameId: 'memory',
    gameName: 'MEMORY',
    genre: 'Sequence Memory Arcade',
    title: 'MEMORY — Free Memory Pattern & Sequence Game | One More Rush',
    description: 'Expand your pattern recall and sequence retention in MEMORY, a challenging visual memory brain training arcade game on One More Rush.',
    h1: '🧠 MEMORY — Visual Sequence & Pattern Game',
    subtitle: 'How much can you remember?',
    type: 'game',
    overview: 'MEMORY is a brain-training pattern sequence game where you must observe, retain, and replicate ever-expanding sequences of glowing tiles and musical tones.',
    objective: 'Watch the sequence illumination and replicate the exact order of activated tiles without making a single error.',
    howToPlay: [
      'Observe the sequence of illuminated tiles and listen to their distinct musical tones.',
      'Wait for the demonstration phase to finish and the player turn indicator to activate.',
      'Click or tap the tiles in the exact chronological order they were illuminated.',
      'Each successful round adds one additional step to the sequence and speeds up playback.',
      'Clear round 10 to unlock the Mastermind achievement badge.',
    ],
    controls: 'Desktop: Mouse Click or Number Keys. Mobile / Tablet: Tap grid cells in order.',
    skillsTested: 'Working Memory Capacity, Pattern Recognition, Sequence Retention.',
    proTip: 'Group sequence steps into chunks of 3 or mentally trace the geometric motion path.',
    flowSteps: ['WATCH SEQUENCE', 'MEMORIZE TILES', 'REPEAT PATTERN', 'EXPAND CHAIN'],
  },
  '/games/color-maze': {
    path: '/games/color-maze',
    gameId: 'color-maze',
    gameName: 'COLOR MAZE',
    genre: 'Labyrinth Pathfinding Arcade',
    title: 'COLOR MAZE — Free Maze & Ball Control Game | One More Rush',
    description: 'Paint every corridor of geometric labyrinth mazes in COLOR MAZE. Test your swipe pathfinding and spatial timing on One More Rush.',
    h1: '🎨 COLOR MAZE — Labyrinth Painter & Sliding Puzzle',
    subtitle: 'Paint every tile. Slide to the finish.',
    type: 'game',
    overview: 'COLOR MAZE is a kinetic sliding labyrinth puzzle where you pilot a paint roller ball through intricate geometric mazes, coating every unpainted tile before the clock runs out.',
    objective: 'Slide the roller through corridors until 100% of the maze floor is covered in vibrant paint.',
    howToPlay: [
      'Swipe or use directional arrow keys to send the roller ball gliding along corridors.',
      'The ball travels in a straight line until colliding with a wall block.',
      'Every tile traversed is permanently coated with glowing paint.',
      'Cover 100% of available floor space to immediately advance to the next level.',
      'Clear level 15+ to earn the Maze Painter achievement in your Rush Locker.',
    ],
    controls: 'Desktop: Arrow Keys or WASD. Mobile / Tablet: 4-Way Directional Touch Swipe.',
    skillsTested: 'Spatial Pathfinding, Route Optimization, Motion Planning, Swipe Precision.',
    proTip: 'Queue your next swipe before the ball reaches a wall to keep rolling at full speed.',
    flowSteps: ['MAZE LOADS', 'SLIDE BALL', 'PAINT CORRIDORS', 'COMPLETE LEVEL'],
  },
  '/daily': {
    path: '/daily',
    breadcrumbName: 'Daily Challenge',
    title: 'DAILY CHALLENGE — Daily Arcade Challenges | One More Rush',
    description: 'Compete in daily rotating Quick Win and Extreme Rush arcade missions. Build your streak, earn Rush Points, and climb leaderboards on One More Rush.',
    h1: '⚡ DAILY CHALLENGE — Rotating Arcade Missions',
    type: 'website',
    overview: 'Every UTC calendar day, One More Rush generates two distinct challenge missions across our arcade lineup: Quick Win (an accessible milestone) and Extreme Rush (a precision mastery challenge). Clear them daily to build your streak and earn Rush Points.',
    features: [
      '+35 Rush Points (RP) for your first Quick Win completion of the day.',
      '+600 Rush Points (RP) for mastering the Extreme Rush challenge.',
      'Daily streak progression unlocking exclusive badges like ONE MORE.',
      'Deterministic calendar rotation synchronized at 00:00 UTC.',
    ],
  },
  '/leaderboard': {
    path: '/leaderboard',
    breadcrumbName: 'Leaderboard',
    title: 'LEADERBOARD — One More Rush Arcade High Scores',
    description: 'View global top scores and personal best arcade records across Aim, Dodge, Stack, Number Rush, Memory, and Color Maze on One More Rush.',
    h1: '🏆 ARCADE LEADERBOARDS — Global High Scores',
    type: 'website',
    overview: 'Track your personal best arcade records and view verified global player achievements across all six skill games. Compare your performance against competitive players worldwide.',
    features: [
      'Game-by-game rankings for Aim, Dodge, Stack, Number Rush, Memory, and Color Maze.',
      'Verified score records tied to registered player handles.',
      'Local personal best tracking for guest players with automatic cloud sync upon sign-in.',
    ],
  },
  '/locker': {
    path: '/locker',
    breadcrumbName: 'Rush Locker',
    title: 'RUSH LOCKER — Cosmetic Frames, Titles & Victory Effects | One More Rush',
    description: 'Customize your arcade profile with avatar frames, prestige titles, celebratory victory effects, and achievement badges in the Rush Locker.',
    h1: '💎 RUSH LOCKER — Cosmetic Workshop & Badges',
    type: 'website',
    overview: 'The Rush Locker is the cosmetic workshop of One More Rush. Spend your earned Rush Points on animated avatar frames, player titles, and celebratory victory effects with zero pay-to-win mechanics.',
    features: [
      '100% cosmetic customizations: avatar frames, player titles, and victory effects.',
      'Achievement badges awarded for genuine skill milestones across all games.',
      'Rush Points earned strictly through gameplay and daily challenge completions.',
    ],
  },
  '/about': {
    path: '/about',
    breadcrumbName: 'About',
    title: 'ABOUT ONE MORE RUSH — Free Online Arcade Platform',
    description: 'Learn about One More Rush, an instant-play browser arcade designed for pure skill, responsive controls, daily challenges, and personal best records.',
    h1: 'ℹ️ ABOUT ONE MORE RUSH — Browser Arcade',
    type: 'website',
    overview: 'One More Rush was created with one philosophy: provide instant, responsive, and skill-testing browser arcade games that feel satisfying to play and master. No ads mid-run, no pay-to-win tricks, and no barriers.',
    features: [
      'Pure skill-based gameplay with instant 60 FPS canvas rendering.',
      'Privacy-first architecture: full guest play with zero tracking.',
      'Fair-play competitive leaderboards and daily challenge rotation.',
    ],
  },
  '/support': {
    path: '/support',
    breadcrumbName: 'Support & FAQ',
    title: 'SUPPORT & FAQ — One More Rush Help Center',
    description: 'Find answers about Rush Points, Daily Challenges, cosmetics, achievements, fair play rules, and submit feedback or bug reports on One More Rush.',
    h1: '🛟 SUPPORT & FAQ — Help Center',
    type: 'website',
    overview: 'Have questions about Rush Points, Daily Challenges, cosmetic unlocks, or account features? Browse our comprehensive FAQ or contact the team directly.',
    features: [
      'Frequently asked questions on Rush Points, streaks, and game mechanics.',
      'Direct bug reporting and community feedback tool.',
      'Official support channel: support.onemorerush@gmail.com.',
    ],
  },
  '/privacy': {
    path: '/privacy',
    breadcrumbName: 'Privacy Policy',
    title: 'PRIVACY POLICY — One More Rush',
    description: 'Read our transparent privacy policy. Learn how One More Rush handles local game progress, authentication, and user data protection.',
    h1: '🔒 PRIVACY POLICY — Transparent Data Practices',
    type: 'website',
    overview: 'One More Rush operates with transparent, privacy-first principles. We prioritize local client-side storage for game progress and collect only minimal credentials when you choose to create an account.',
    features: [
      'Guest progress is stored 100% locally in your browser LocalStorage.',
      'Cloud accounts use secure, authenticated email and password storage.',
      'Zero third-party tracking scripts or advertising trackers.',
    ],
  },
  '/terms': {
    path: '/terms',
    breadcrumbName: 'Terms of Use',
    title: 'TERMS OF USE & FAIR PLAY — One More Rush',
    description: 'Review the terms of service, virtual Rush Points rules, leaderboard integrity guidelines, and fair play standards for One More Rush.',
    h1: '📜 TERMS OF USE & FAIR PLAY GUIDELINES',
    type: 'website',
    overview: 'Please review the terms of service and fair play guidelines for One More Rush. Rush Points (RP) are strictly virtual entertainment points with no monetary cash-out value.',
    features: [
      'Fair play guidelines prohibiting automated bots and exploit scripts.',
      'Virtual currency terms: Rush Points are non-monetary cosmetic tokens.',
      'Leaderboard integrity and competitive community standards.',
    ],
  },
};

export const AUTH_ROUTE_SEO = {
  '/login': {
    path: '/login',
    title: 'SIGN IN — One More Rush',
    description: 'Sign in to your One More Rush player account to manage your profile and global records.',
    noindex: true,
  },
  '/signup': {
    path: '/signup',
    title: 'CREATE ACCOUNT — One More Rush',
    description: 'Create a free One More Rush account to claim your player username and save your progress.',
    noindex: true,
  },
  '/profile': {
    path: '/profile',
    title: 'PLAYER PROFILE — One More Rush',
    description: 'View your player profile, equipped cosmetics, title, and Rush Points on One More Rush.',
    noindex: true,
  },
  '/404': {
    path: '/404',
    title: 'PAGE NOT FOUND — One More Rush',
    description: 'The page you are looking for does not exist on One More Rush.',
    noindex: true,
  },
};
